application: nsurank 
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(js|css))
  static_files: static/\1
  upload: static/.*
  expiration: "0d"

- url: /(.*\.(html|htm|gif|jpg|png|ico))
  static_files: static/\1
  upload: static/.*
  expiration: "0d"

- url: /.*
  script: main.py

