application: nsurank 
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /(.*\.(js|css))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /(.*\.(html|htm|gif|jpg|png|ico))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /.*
  script: main.py

